#!/usr/bin/env bash

docker run \
    --rm -it \
    --privileged \
    --net=host \
    --cap-add SYS_ADMIN \
    --ipc=host \
    -v /:/host:shared \
    -v /run:/run:shared \
    -v ${PWD}:/etc/netappdvp \
    --name=ndvp \
    netapp/ndvp:17.07 ash

