.catalog:
  name: "nDVP"
  version: "17.07"
  description: "NetApp Docker Volume Plugin (nDVP)"
  questions:
    # Common settings
    - variable: "STORAGE_PREFIX"
      description: "Prefix for created storage objects"
      label: "Storage Prefix"
      required: false
      default: "netappdvp_"
      type: "string"

    - variable: "DEBUG_ENABLED"
      description: "Enable debugging output in logs"
      label: "Debug Logging"
      required: false
      default: false
      type: "boolean"

    # ONTAP-NAS settings
    - variable: "MANAGEMENT_LIF"
      description: "IP address of clustered Data ONTAP management LIF"
      label: "Management LIF"
      required: true
      type: "string"

    - variable: "DATA_LIF"
      description: "IP address of protocol LIF; will be derived if not specified"
      label: "Data LIF"
      required: false
      type: "string"

    - variable: "SVM"
      description: "Storage Virtual Machine to use for provisioning"
      label: "SVM"
      required: true
      type: "string"

    - variable: "AGGREGATE"
      description: "Default aggregate for creating ontap storage objects"
      label: "Aggregate"
      required: true
      type: "string"

    - variable: "USER_NAME"
      description: "Username for connecting to your storage system"
      label: "User Name"
      required: true
      default: "vsadmin"
      type: "string"
    - variable: "USER_PASSWORD"
      description: "Password for connecting to your storage system"
      label: "Password"
      required: true
      type: "password"

    # ONTAP-SAN defaults settings
    - variable: "SPACE_RESERVE"
      description: "Space reservation mode; 'none' (thin provisioned) or 'volume' (thick)"
      label: "Space Reserve"
      required: false
      default: "none"
      type: "string"

    - variable: "SNAPSHOT_POLICY"
      description: "Snapshot policy to use, default is 'none'"
      label: "Snapshot Policy"
      required: false
      default: "none"
      type: "string"

    - variable: "SPLIT_ON_CLONE"
      description: "Split a clone from its parent upon creation, defaults to 'false'"
      label: "Split On Clone"
      required: false
      default: "false"
      type: "string"

    # Common settings
    - variable: "SIZE"
      description: "Optional default size for new volumes. Default: '1G'"
      label: "Volume Size"
      required: false
      default: "1G"
      type: "string"

    - variable: "VOLUME_DRIVER_NAME"
      description: "Name to use for this plugin instance with Docker:  docker volume create -d <volume driver name>"
      label: "Volume Driver Name"
      required: true
      default: "netapp"
      type: "string"



netapp-ontap-san:
  labels:
    io.rancher.scheduler.global: 'true'
  metadata:
    version: 1
    storageDriverName: "ontap-san"
    debug: true
    storagePrefix: "${STORAGE_PREFIX}"
    managementLIF: "${MANAGEMENT_LIF}"
    dataLIF: "${DATA_LIF}"
    svm: "${SVM}"
    username: "${USER_NAME}"
    password: "${USER_PASSWORD}"
    aggregate: "${AGGREGATE}"
    defaults:
      spaceReserve: "${SPACE_RESERVE}"
      snapshotPolicy: "${SNAPSHOT_POLICY}"
      splitOnClone: "${SPLIT_ON_CLONE}"
      size: "${SIZE}"
    volumeDriverName: "${VOLUME_DRIVER_NAME}"
  storage_driver:
    name: "${VOLUME_DRIVER_NAME}"
    scope: environment
    volume_access_mode: singleHostRW

